name: summerhack-23
on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  merge:
    name: Build-lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client/

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - name: Linting
        run: npm format:lint:fix
      - name: Build app
        run: npm run build
